install: 
  - wget "https://raw.githubusercontent.com/globalbioticinteractions/globinizer/master/check-dataset.sh" -O check-dataset.sh
  - chmod +x check-dataset.sh

script: ./check-dataset.sh ${TRAVIS_REPO_SLUG}

notifications:
  email:
    recipients:
      - jhpoelen@xs4all.nl
      - eolspecies@gmail.com
      - SchulzK@si.edu
